# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Build & publish all images

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # Note: When modifying this job, copy modifications to all other workflow image jobs.
  all_component_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: coturn
          context: addons/coturn

        - name: coturn-web
          context: addons/coturn-web

        - name: gst-web
          context: addons/gst-web

        - name: gstreamer
          version_suffix: -ubuntu20.04
          build_args: |
            DISTRIB_RELEASE=20.04
          context: addons/gstreamer

        - name: gstreamer
          version_suffix: -ubuntu22.04
          build_args: |
            DISTRIB_RELEASE=22.04
          context: addons/gstreamer

        - name: gstreamer
          version_suffix: -ubuntu20.04
          build_args: |
            DISTRIB_RELEASE=20.04
          context: addons/gstreamer
          platforms: linux/arm64

        - name: gstreamer
          version_suffix: -ubuntu22.04
          build_args: |
            DISTRIB_RELEASE=22.04
          context: addons/gstreamer
          platforms: linux/arm64

        - name: js-interposer
          version_suffix: -ubuntu20.04
          build_args: |
            DISTRIB_RELEASE=20.04
            PKG_NAME=selkies-js-interposer
            PKG_VERSION=0.0.0
          context: addons/js-interposer
          dockerfile: Dockerfile.ubuntu_debpkg

        - name: js-interposer
          version_suffix: -ubuntu22.04
          build_args: |
            DISTRIB_RELEASE=22.04
            PKG_NAME=selkies-js-interposer
            PKG_VERSION=0.0.0
          context: addons/js-interposer
          dockerfile: Dockerfile.ubuntu_debpkg

        - name: js-interposer
          version_suffix: -ubuntu20.04
          build_args: |
            DISTRIB_RELEASE=20.04
            PKG_NAME=selkies-js-interposer
            PKG_VERSION=0.0.0
          context: addons/js-interposer
          dockerfile: Dockerfile.ubuntu_debpkg
          platforms: linux/arm64

        - name: js-interposer
          version_suffix: -ubuntu22.04
          build_args: |
            DISTRIB_RELEASE=22.04
            PKG_NAME=selkies-js-interposer
            PKG_VERSION=0.0.0
          context: addons/js-interposer
          dockerfile: Dockerfile.ubuntu_debpkg
          platforms: linux/arm64

        - name: infra-gcp-installer
          context: infra/gce/installer-image
          diff: infra/gce

        - name: py-build
          build_args: |
            PACKAGE_VERSION=0.0.0.dev0
          context: .

    name: ${{ matrix.name }}${{ matrix.version_suffix }}-${{ matrix.platforms || 'linux/amd64' }} image build & publish
    steps:
    - uses: actions/checkout@v4

    - name: Build & publish ${{ matrix.name }} image
      uses: ./.github/actions/build_and_publish_image
      with:
        build_args: ${{ matrix.build_args }}
        dockerfile: ${{ matrix.dockerfile }}
        context: ${{ matrix.context }}
        subproject: ${{ matrix.name }}
        platforms: ${{ matrix.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ github.ref_name }}${{ matrix.version_suffix }}

  # Note: When modifying this job, copy modifications to all other workflows' image jobs.
  all_example_images:
    needs: all_component_images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: gst-py-example
          version_suffix: -ubuntu20.04
          build_args: |
            PACKAGE_VERSION=0.0.0.dev0
            DISTRIB_RELEASE=20.04
            GSTREAMER_BASE_IMAGE_RELEASE=${{ github.ref_name }}
            PY_BUILD_IMAGE=ghcr.io/${{ github.repository }}/py-build:${{ github.ref_name }}
            WEB_IMAGE=ghcr.io/${{ github.repository }}/gst-web:${{ github.ref_name }}
            JS_BASE_IMAGE_RELEASE=${{ github.ref_name }}
            JS_BASE_IMAGE=ghcr.io/${{ github.repository }}/js-interposer
          dockerfile: Dockerfile.example
          context: .

        - name: gst-py-example
          version_suffix: -ubuntu22.04
          build_args: |
            PACKAGE_VERSION=0.0.0.dev0
            DISTRIB_RELEASE=22.04
            GSTREAMER_BASE_IMAGE_RELEASE=${{ github.ref_name }}
            PY_BUILD_IMAGE=ghcr.io/${{ github.repository }}/py-build:${{ github.ref_name }}
            WEB_IMAGE=ghcr.io/${{ github.repository }}/gst-web:${{ github.ref_name }}
            JS_BASE_IMAGE_RELEASE=${{ github.ref_name }}
            JS_BASE_IMAGE=ghcr.io/${{ github.repository }}/js-interposer
          dockerfile: Dockerfile.example
          context: .

    name: ${{ matrix.name }}${{ matrix.version_suffix }}-${{ matrix.platforms || 'linux/amd64' }} image build & publish
    steps:
    - uses: actions/checkout@v4

    - name: Build & publish ${{ matrix.name }} image
      uses: ./.github/actions/build_and_publish_image
      with:
        build_args: ${{ matrix.build_args }}
        dockerfile: ${{ matrix.dockerfile }}
        context: ${{ matrix.context }}
        subproject: ${{ matrix.name }}
        platforms: ${{ matrix.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ github.ref_name }}${{ matrix.version_suffix }}
