# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Build & publish all images

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # Note: When modifying this job, copy modifications to all other workflow image jobs.
  all_component_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: coturn
          context: addons/coturn
          platforms: linux/amd64,linux/arm64

        - name: coturn-web
          context: addons/coturn-web
          platforms: linux/amd64,linux/arm64

        - name: gst-web
          context: addons/gst-web

        - name: gstreamer
          version_suffix: -ubuntu20.04
          build_args: |
            DISTRIB_RELEASE=20.04
          context: addons/gstreamer
          platforms: linux/amd64 #,linux/arm64

        - name: gstreamer
          version_suffix: -ubuntu22.04
          build_args: |
            DISTRIB_RELEASE=22.04
          context: addons/gstreamer
          platforms: linux/amd64 #,linux/arm64

        - name: js-interposer
          version_suffix: -ubuntu20.04
          build_args: |
            DISTRIB_RELEASE=20.04
            PKG_NAME=selkies-js-interposer
            PKG_VERSION=0.0.0
          context: addons/js-interposer
          dockerfile: Dockerfile.ubuntu_debpkg
          platforms: linux/amd64,linux/arm64

        - name: js-interposer
          version_suffix: -ubuntu22.04
          build_args: |
            DISTRIB_RELEASE=22.04
            PKG_NAME=selkies-js-interposer
            PKG_VERSION=0.0.0
          context: addons/js-interposer
          dockerfile: Dockerfile.ubuntu_debpkg
          platforms: linux/amd64,linux/arm64

        - name: infra-gcp-installer
          context: infra/gce/installer-image
          diff: infra/gce

        - name: py-build
          build_args: |
            PACKAGE_VERSION=0.0.0.dev0
          context: .

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
    - uses: actions/checkout@v4

    - name: Build & publish ${{ matrix.name }} image
      uses: ./.github/actions/build_and_publish_image
      with:
        build_args: ${{ matrix.build_args }}
        context: ${{ matrix.context }}
        dockerfile: ${{ matrix.dockerfile }}
        platforms: ${{ matrix.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        subproject: ${{ matrix.name }}
        tags: ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ github.ref_name }}${{ matrix.version_suffix }}

  # Note: When modifying this job, copy modifications to all other workflow image jobs.
  all_example_images:
    needs: all_component_images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: gst-py-example
          version_suffix: -ubuntu20.04
          build_args: |
            PACKAGE_VERSION=0.0.0.dev0
            DISTRIB_RELEASE=20.04
            GSTREAMER_BASE_IMAGE_RELEASE=${{ github.ref_name }}
            PY_BUILD_IMAGE=ghcr.io/${{ github.repository }}/py-build:${{ github.ref_name }}
            WEB_IMAGE=ghcr.io/${{ github.repository }}/gst-web:${{ github.ref_name }}
            JS_BASE_IMAGE_RELEASE=${{ github.ref_name }}
            JS_BASE_IMAGE=ghcr.io/${{ github.repository }}/js-interposer
          dockerfile: Dockerfile.example
          context: .

        - name: gst-py-example
          version_suffix: -ubuntu22.04
          build_args: |
            PACKAGE_VERSION=0.0.0.dev0
            DISTRIB_RELEASE=22.04
            GSTREAMER_BASE_IMAGE_RELEASE=${{ github.ref_name }}
            PY_BUILD_IMAGE=ghcr.io/${{ github.repository }}/py-build:${{ github.ref_name }}
            WEB_IMAGE=ghcr.io/${{ github.repository }}/gst-web:${{ github.ref_name }}
            JS_BASE_IMAGE_RELEASE=${{ github.ref_name }}
            JS_BASE_IMAGE=ghcr.io/${{ github.repository }}/js-interposer
          dockerfile: Dockerfile.example
          context: .

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
    - uses: actions/checkout@v4

    - name: Build & publish ${{ matrix.name }} image
      uses: ./.github/actions/build_and_publish_image
      with:
        build_args: ${{ matrix.build_args }}
        context: ${{ matrix.context }}
        dockerfile: ${{ matrix.dockerfile }}
        platforms: ${{ matrix.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        subproject: ${{ matrix.name }}
        tags: ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ github.ref_name }}${{ matrix.version_suffix }}

  # Note: When modifying this job, copy modifications to all other workflow image jobs.
  upload_assets:
    needs: all_component_images
    runs-on: ubuntu-latest
    env:
      TEMP_DIR: /tmp
    strategy:
      matrix:
        include:
        - name: gst-web
          target: /usr/share/nginx/html

        - name: gstreamer
          version_suffix: -ubuntu20.04
          target: /opt/gstreamer

        - name: gstreamer
          version_suffix: -ubuntu22.04
          target: /opt/gstreamer

        # - name: gstreamer
        #   version_suffix: -ubuntu20.04
        #   target: /opt/gstreamer
        #   platforms: linux/arm64

        # - name: gstreamer
        #   version_suffix: -ubuntu22.04
        #   target: /opt/gstreamer
        #   platforms: linux/arm64

        - name: js-interposer
          version_suffix: -ubuntu20.04
          target: /opt/selkies-js-interposer_0.0.0.deb

        - name: js-interposer
          version_suffix: -ubuntu22.04
          target: /opt/selkies-js-interposer_0.0.0.deb

        - name: js-interposer
          version_suffix: -ubuntu20.04
          target: /opt/selkies-js-interposer_0.0.0.deb
          platforms: linux/arm64

        - name: js-interposer
          version_suffix: -ubuntu22.04
          target: /opt/selkies-js-interposer_0.0.0.deb
          platforms: linux/arm64

        - name: py-build
          target: /opt/pypi/dist/selkies_gstreamer-0.0.0.dev0-py3-none-any.whl

    name: ${{ matrix.name }}${{ matrix.version_suffix }}_${{ matrix.platforms || 'linux/amd64' }} build artifact extraction & upload
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: ${{ matrix.name }}${{ matrix.version_suffix }}_${{ matrix.platforms || 'linux/amd64' }} build artifact extraction
      id: extract
      run: |
        docker container create --platform="${{ matrix.platforms || 'linux/amd64' }}" --name="${{ matrix.name }}${{ matrix.version_suffix }}_${{ matrix.platforms || 'linux/amd64' }}" "ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ github.ref_name }}${{ matrix.version_suffix }}"
        DEST_PATH="${{ env.TEMP_DIR }}/${{ matrix.name }}${{ matrix.version_suffix }}_${{ matrix.platforms || 'linux/amd64' }}"
        mkdir -pm755 "${DEST_PATH}"
        docker container cp "${{ matrix.name }}${{ matrix.version_suffix }}_${{ matrix.platforms || 'linux/amd64' }}:${{ matrix.target }}" "${DEST_PATH}"
        docker container rm -f -l -v "${{ matrix.name }}${{ matrix.version_suffix }}_${{ matrix.platforms || 'linux/amd64' }}"

    - name: ${{ matrix.name }}${{ matrix.version_suffix }}_${{ matrix.platforms || 'linux/amd64' }} upload
      id: upload
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        overwrite: true
        name: ${{ matrix.name }}${{ matrix.version_suffix }}_${{ matrix.platforms || 'linux/amd64' }}
        path: ${{ env.TEMP_DIR }}/${{ matrix.name }}${{ matrix.version_suffix }}_${{ matrix.platforms || 'linux/amd64' }}/${{ matrix.target }}
